config/routes.rb
IdeaBlender::Application.routes.draw do
  
  resources :ideas
  root :to => 'ideas#index'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :author, :category, :content, :multi_line

  def self.random
    Idea.order("RANDOM()").first
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['content LIKE ? OR category LIKE ?', "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    if params[:keyword]
      @ideas = Idea.search(params[:keyword])
    else
      @ideas = Idea.all.reverse
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    if params[:mode] == "random"
      @idea = Idea.random
    else
      @idea = Idea.find(params[:id])
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])
    if params[:multi_line] == 0
      respond_to do |format|
        if @idea.save
          format.html { redirect_to new_idea_path(author: @idea.author), notice: 'Idea was successfully created.' }
          format.json { render json: @idea, status: :created, location: @idea }
        else
          format.html { render action: "new" }
          format.json { render json: @idea.errors, status: :unprocessable_entity }
        end
      end
    else
      @idea_collection = @idea.content.split(/\r?\n/)
      @idea_collection.each do |idc|
        Idea.create(author: @idea.author, content: idc, category: @idea.category)
      end
      redirect_to ideas_path
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def icon_activable_link_to(element_type, icon_name, text, path, options = {})
    content_tag element_type, class: "#{'active' if request.path == path}" do 
      link_to path, options do
        "<i class='icon-#{icon_name}'></i> #{text}".html_safe
      end
    end
  end

  def time_ago_with_tense(time)
    if Time.now > time then time_ago_in_words(time) + " ago"
    else                    time_ago_in_words(time) + " from now" end
  end
  
end

app/helpers/ideas_helper.rb
module IdeasHelper
  def label_color(category)
    if category.length > 10
      ""
    elsif category.length > 8
      "label-warning"
    elsif category.length > 7
      "label-success"
    elsif category.length > 6
      "label-important"
    else
      "label-info"
    end
  end
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, size: '14x3' %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author, value: params[:author] %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= check_box_tag(:multi_line) %>
    <%= label_tag(:multi_line,  "Add with multi line") %>
  </div>
  <div class="actions">
    <%= f.submit 'Add idea', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/ideas/_idea.html.erb
<div class="span10 clearfix">
<blockquote>
  <div class="span9">
    <p><span class="label <%=label_color idea.category %>"><%= idea.category %></span> <%= idea.content %></p>
    <small><i class="icon-comment-alt"></i> <%= idea.author %><cite title="datetime"> at <%= time_ago_with_tense idea.created_at %>.</cite></small>
    <hr />
  </div>
  <div class="edit-delete-icons">
    <%= link_to "", edit_idea_path(idea), class: "icon-pencil" %>
    <%= link_to "", idea, method: :delete, data: { confirm: 'Are you sure?' }, class: 'icon-trash' %>
  </div>
</blockquote>
</div>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<div class="span12">
  <div class="well">
    <div class="add-idea-button">
      <%= link_to " New idea", new_idea_path, class: 'icon-lightbulb btn btn-success pull-right' %>
    </div>
    <div class="container">
      <% if params[:keyword] %>
        <%= "<h4>Search idea with keyword: #{params[:keyword]} </h4>".html_safe %>
      <% else %>
        <h3>Blend Ideas</h3>
      <% end %>
    </div>
    <hr />
    <div class="container">
      <div class="span10">
        <%= render @ideas %>
      </div>
    </div>
  </div>

<br />

app/views/ideas/new.html.erb
<div class="well">
  <h1>New idea</h1>
  <hr />
  <%= render 'form' %>

  <%= link_to 'Back', ideas_path %>
</div>
<br />
<br />
<br />

app/views/ideas/show.html.erb
<br />
<br />
<div class="well">
  <h3><%= params[:mode].camelize if params[:mode] %> Idea</h3>
  <hr />
  <%= render @idea %>
  <br />
  <br />
  <br />
  <br />
</div>
<br />
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaBlender</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">IdeaBlender</a>
      <div class="nav-collapse collapse navbar-inverse-collapse">
        <ul class="nav">
          <%= icon_activable_link_to('li', 'home', 'Home', ideas_path) %>
          <%= icon_activable_link_to('li', 'lightbulb', 'New Idea', new_idea_path) %>
          <%= icon_activable_link_to('li', 'random', 'Random', idea_path(Idea.first, mode: 'random')) %>
        </ul>
        <form class="navbar-search pull-right" method="get" action="<%= ideas_url %>">
          <input name="keyword" type="text" class="search-query span2" placeholder="Any idea?" value="<%= params[:keyword] if params[:keyword] %>">
        </form>
      </div><!-- /.nav-collapse -->
    </div>
  </div><!-- /navbar-inner -->
</div>
<div class="container">
  <%= yield %>
  <br />
  <br />
  <br />
</div>

<div class="navbar navbar-inverse navbar-fixed-bottom">
  <div class="navbar-inner">
    <div class="footer-text">
      made with <i class="icon-heart"></i> in bangkok | awesome ideas by  <i class="icon-group"></i> ploy, prang, looknam, wut, t0n | coding by <i class="icon-github"></i> goodfeel (t0n) -  powered by ruby on rails.
    </div>
  </div>
</div>
</body>
</html>